### ISSUE TITLE
LocalLLM using llama_cpp_python with the mistral-nemo:12b-instruct-2407-q8_0 giving error

### ISSUE THREAD

**Issue by gl2007** [bartolli/mcp-llm-bridge#3]
Hello, I am trying to run the sample you have with the same test.db. However, after configuring the endpoint as below       
```
llm_config=LLMConfig(
            api_key="ollama",  # Can be any string for local testing
            model="mistral-nemo:12b-instruct-2407-q8_0",
            base_url="http://localhost:8000/v1"  # Point to your local model's endpoint
        )"
```

I am getting error logged in my LocalLLM endpoint as below: 

```
INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
Exception: [{'type': 'literal_error', 'loc': ('body', 'messages', 2, 'typed-dict', 'role'), 'msg': "Input should be 'system'", 'input': 'assistant', 'ctx': {'expected': "'system'"}}, {'type': 'literal_error', 'loc': ('body', 'messages', 2, 'typed-dict', 'role'), 'msg': "Input should be 'user'", 'input': 'assistant', 'ctx': {'expected': "'user'"}}, {'type': 'list_type', 'loc': ('body', 'messages', 2, 'typed-dict', 'tool_calls'), 'msg': 'Input should be a valid list', 'input': None}, {'type': 'literal_error', 'loc': ('body', 'messages', 2, 'typed-dict', 'role'), 'msg': "Input should be 'tool'", 'input': 'assistant', 'ctx': {'expected': "'tool'"}}, {'type': 'missing', 'loc': ('body', 'messages', 2, 'typed-dict', 'tool_call_id'), 'msg': 'Field required', 'input': {'role': 'assistant', 'content': '[{"name": "read_query", "arguments": {"query": "SELECT * FROM products ORDER BY price DESC"}}, {"name": "append_insight", "arguments": {"insight": "Most expensive product in the database is a rare, antique item worth $1000"}}]', 'tool_calls': None}}, {'type': 'literal_error', 'loc': ('body', 'messages', 2, 'typed-dict', 'role'), 'msg': "Input should be 'function'", 'input': 'assistant', 'ctx': {'expected': "'function'"}}, {'type': 'missing', 'loc': ('body', 'messages', 2, 'typed-dict', 'name'), 'msg': 'Field required', 'input': {'role': 'assistant', 'content': '[{"name": "read_query", "arguments": {"query": "SELECT * FROM products ORDER BY price DESC"}}, {"name": "append_insight", "arguments": {"insight": "Most expensive product in the database is a rare, antique item worth $1000"}}]', 'tool_calls': None}}]
Traceback (most recent call last):

```
Do you know how to get this working? 

Note: the LocalLLM works with any model that I download and configure it in and I have success in another app that is able to talk to it and get chat messages back, I can play with other models to see if it is related to model?

Update: changed it to Qwen2.5-Coder-7B.Q8_0 and still the same error.

**Comment by bartolli** [comment]
I see that both the Uvicorn and llama.cpp servers are using the same port (8000). Could you try changing one of them and test it again?

**Comment by gl2007** [comment]
Actually, llama.cpp server is running the Uvicorn so its one and the same. From the error, I guess llama was expecting "system" somewhere in the system prompt. I changed the system prompt to 

`system_prompt="system: You are a helpful assistant that can use tools to help answer questions."`

and I then got a response like below, but no error. 

`Response: [{"name": "read_query", "arguments": {"query": "SELECT title, price FROM products ORDER BY price DESC"}}]`

So it seems like it wasn't able to call that tool?

**Comment by bartolli** [comment]
Did you try to add /v1 to specify the open api endpoint? I see that you're missing this in your request.

**Comment by gl2007** [comment]
This is my configuration which already has v1 included. Can you please point me to where in the request you are seeing it missing? The url seen in the error in INFO is the Url where the Uvicorn is running which doesn't include the /v1 but that is how the llama-cpp-python is showing its url which is not in my control.

```
llm_config=LLMConfig(
            api_key="ollama",  # Can be any string for local testing
            model="mistral-nemo:12b-instruct-2407-q8_0",
            base_url="http://localhost:8000/v1"  # Point to your local model's endpoint
        )"
```

**Comment by bartolli** [comment]
With ollama is fine, but looking at the llama.cpp server docs, we need to be more precise with the endpoint. 
Try updating your config to:
```
llm_config=LLMConfig(
    api_key="ollama",  
    model="mistral-nemo:12b-instruct-2407-q8_0",
    base_url="http://localhost:8000/v1/chat/completions"  # This is the key change!
)
```
Give that a try and let me know if it works better.

**Comment by gl2007** [comment]
Still a no go. In fact, my llama-cpp-python returned 404 as request was being posted to "v1/chat/completions/chat/completions" (see attached image) which is incorrect whereas if I keep it just as v1, then I get 200 but response is the query itself which I posted above in my previous response.

I am leaning towards conclusion that llama-cpp-python isn't fully a compatible OpenAI Web drop in as claimed :(.

![error-with-chat-completions-added](https://github.com/user-attachments/assets/e2780dbe-eafd-476b-9627-9a610bf1503f)

**Comment by bartolli** [comment]
Ok, try to remove the /v1 from the script config:
```
llm_config=LLMConfig(
    api_key="ollama",  
    model="mistral-nemo:12b-instruct-2407-q8_0",
    base_url="http://localhost:8000"  # try this
)
```

**Comment by gl2007** [comment]
I get error 404 back from the llama-cpp-python, when v1 is removed. See attached image. 

Error I see in the mcp-llm-bridge is `"Error processing message: Error code: 404 - {'detail': 'Not Found'}"`

![error-without-v1-added](https://github.com/user-attachments/assets/754ee91e-d8d3-4e74-bd01-f4df70b43d67)

**Comment by bartolli** [comment]
Ok.. it looks like llama.cpp doesn't support tool calling:
[https://github.com/QwenLM/Qwen2.5/issues/822#issuecomment-2257957365](https://github.com/QwenLM/Qwen2.5/issues/822#issuecomment-2257957365)

Here's what I've reproduced as well:

```
got exception: {"code":500,"message":"Unsupported param: tools","type":"server_error"}
request: POST /v1/chat/completions 127.0.0.1 500
```

I'd advice you to install ollama or lm-studio
